import 'package:dartz/dartz.dart';

import '../models/exercise_model.dart';

abstract class ExerciseRepository {
  Future<Either<String, List<Exercise>>> getExercises();
}

class ExerciseRepositoryImpl implements ExerciseRepository {
  // TODO: mock data — পরে ApiClient দিয়ে server থেকে fetch করবেন
  @override
  Future<Either<String, List<Exercise>>> getExercises() async {
    try {
      await Future.delayed(const Duration(milliseconds: 300));
      return Right(_mockExercises);
    } catch (e) {
      return const Left('এক্সারসাইজ লোড করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।');
    }
  }

  static final List<Exercise> _mockExercises = [
    Exercise(
      id: 'e1',
      name: 'Barbell Bench Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'The king of chest exercises for building mass and strength.',
      instructions: const [
        'Lie flat on bench with feet firmly on ground',
        'Grip barbell slightly wider than shoulder width',
        'Lower bar to mid-chest with controlled motion',
        'Press up powerfully, driving through chest',
        'Keep core tight and maintain natural arch',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 45,
      defaultSets: 4,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e2',
      name: 'Incline Dumbbell Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Targets upper chest for complete pectoral development.',
      instructions: const [
        'Set bench to 30-45 degree incline',
        'Hold dumbbells at shoulder level',
        'Press dumbbells up until arms extended',
        'Lower with control back to start position',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 36,
      defaultSets: 4,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e3',
      name: 'Dips (Chest Variation)',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.compound,
      description: 'Bodyweight exercise for lower chest development.',
      instructions: const [
        'Grip parallel bars and lift body up',
        'Lean torso forward slightly',
        'Lower body until shoulders below elbows',
        'Push back up to starting position',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 30,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e4',
      name: 'Pull-Ups',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Classic bodyweight exercise for a wider, stronger back.',
      instructions: const [
        'Grip bar slightly wider than shoulders',
        'Hang with arms fully extended',
        'Pull body up until chin clears bar',
        'Lower with control back to start',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 40,
      defaultSets: 4,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e5',
      name: 'Overhead Shoulder Press',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Builds strong, well-rounded shoulders.',
      instructions: const [
        'Hold dumbbells at shoulder height',
        'Press weights straight overhead',
        'Lower with control back to shoulders',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 28,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e6',
      name: 'Barbell Bicep Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Isolation movement to build bigger, stronger biceps.',
      instructions: const [
        'Hold barbell with underhand grip',
        'Curl bar up while keeping elbows still',
        'Squeeze at the top, lower with control',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 22,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e7',
      name: 'Flat Dumbbell Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Great alternative to barbell bench press with greater range of motion and stabilization demand.',
      instructions: const [
        'Lie flat on bench holding a dumbbell in each hand',
        'Press dumbbells up until arms are extended',
        'Lower with control until elbows are just below torso',
        'Press back up while squeezing the chest',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 40,
      defaultSets: 4,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e8',
      name: 'Decline Barbell Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.compound,
      description: 'Emphasizes the lower chest with a decline bench angle.',
      instructions: const [
        'Set bench to a 15-30 degree decline',
        'Grip barbell slightly wider than shoulder width',
        'Lower bar to lower chest with control',
        'Press up powerfully to starting position',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 42,
      defaultSets: 4,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e9',
      name: 'Cable Chest Fly',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Isolation movement that keeps constant tension on the chest through the full range of motion.',
      instructions: const [
        'Stand between two cable stacks with handles at chest height',
        'Step forward slightly with a soft bend in the elbows',
        'Bring handles together in front of chest in an arcing motion',
        'Slowly return to starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 24,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e10',
      name: 'Pec Deck Machine',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Machine-based isolation exercise ideal for beginners learning the chest fly motion.',
      instructions: const [
        'Sit with back flat against the pad',
        'Place forearms on the machine pads',
        'Bring pads together in front of chest',
        'Return slowly to the starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 22,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e11',
      name: 'Push-Ups',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Classic bodyweight movement that builds chest, shoulder, and tricep strength.',
      instructions: const [
        'Start in a plank position with hands under shoulders',
        'Lower body until chest nearly touches the floor',
        'Push back up to full arm extension',
        'Keep core braced throughout',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e12',
      name: 'Incline Push-Ups',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Easier push-up variation that reduces load while still building chest strength.',
      instructions: const [
        'Place hands on an elevated surface such as a bench',
        'Lower chest toward the surface with control',
        'Push back up to full arm extension',
        'Keep body in a straight line',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e13',
      name: 'Cable Crossover',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'High-cable variation that targets the lower and inner chest.',
      instructions: const [
        'Set cables to the highest position',
        'Step forward with a slight forward lean',
        'Pull handles down and across the body',
        'Return slowly to the starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 26,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e14',
      name: 'Smith Machine Bench Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Guided-bar variation of the bench press that helps with stability and control.',
      instructions: const [
        'Lie on a flat bench under the Smith machine bar',
        'Unrack the bar and lower to mid-chest',
        'Press up until arms are extended',
        'Repeat with controlled tempo',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 38,
      defaultSets: 4,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e15',
      name: 'Landmine Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Shoulder-friendly pressing movement using a landmine attachment.',
      instructions: const [
        'Hold the end of the barbell at chest height',
        'Press the bar up and slightly forward',
        'Lower with control back to chest height',
        'Keep core tight throughout the movement',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 32,
      defaultSets: 3,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e16',
      name: 'Svend Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Plate-squeeze pressing movement that creates intense inner-chest activation.',
      instructions: const [
        'Hold a weight plate between both palms at chest height',
        'Squeeze the plate firmly throughout the movement',
        'Press the plate straight out in front of the chest',
        'Bring back to chest with control',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 16,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e17',
      name: 'Machine Chest Press',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Beginner-friendly pressing machine that removes the need for balance and stabilization.',
      instructions: const [
        'Adjust seat so handles are at chest height',
        'Press handles forward until arms are extended',
        'Return with control back to the starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 30,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e18',
      name: 'Weighted Dips',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.compound,
      description: 'Advanced dip variation with added resistance for continued chest and tricep growth.',
      instructions: const [
        'Attach weight via a belt or hold a dumbbell between the feet',
        'Lower body until shoulders are below elbows',
        'Push back up to full arm extension',
        'Keep torso leaned slightly forward',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 44,
      defaultSets: 3,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e19',
      name: 'Decline Dumbbell Fly',
      muscleGroup: MuscleGroup.chest,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'Fly variation on a decline bench for targeting the lower chest fibers.',
      instructions: const [
        'Lie on a decline bench holding a dumbbell in each hand',
        'Lower the dumbbells out to the sides with a slight elbow bend',
        'Bring the dumbbells back together above the chest',
        'Control the weight throughout the movement',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 28,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e20',
      name: 'Deadlift',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.compound,
      description: 'Full-body compound lift that builds tremendous back, glute, and hamstring strength.',
      instructions: const [
        'Stand with feet hip-width apart, bar over mid-foot',
        'Bend down and grip the bar just outside the legs',
        'Drive through the floor and stand up tall, keeping the bar close',
        'Lower the bar back down with control',
      ],
      estimatedMinutes: 5,
      estimatedKcal: 55,
      defaultSets: 4,
      defaultRestSeconds: 120,
    ),
    Exercise(
      id: 'e21',
      name: 'Barbell Bent-Over Row',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Classic rowing movement for building back thickness.',
      instructions: const [
        'Hinge at the hips holding a barbell with an overhand grip',
        'Keep back flat and pull the bar toward the lower ribs',
        'Squeeze shoulder blades together at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 42,
      defaultSets: 4,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e22',
      name: 'Lat Pulldown',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Machine-based movement that builds width in the back, great for beginners still developing pull-up strength.',
      instructions: const [
        'Grip the bar wider than shoulder width',
        'Pull the bar down to upper chest while leaning back slightly',
        'Squeeze shoulder blades at the bottom',
        'Return with control to the starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 32,
      defaultSets: 4,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e23',
      name: 'Seated Cable Row',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Horizontal pulling movement that targets the mid-back.',
      instructions: const [
        'Sit with feet on the platform, knees slightly bent',
        'Grip the handle and pull toward the lower abdomen',
        'Squeeze shoulder blades together',
        'Extend arms back out with control',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 30,
      defaultSets: 4,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e24',
      name: 'T-Bar Row',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Heavy rowing variation that builds overall back thickness.',
      instructions: const [
        'Straddle the bar with a neutral torso lean',
        'Pull the handles toward the chest',
        'Squeeze the back at the top of the movement',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 40,
      defaultSets: 4,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e25',
      name: 'Single-Arm Dumbbell Row',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Unilateral rowing movement that helps correct strength imbalances.',
      instructions: const [
        'Place one knee and hand on a bench for support',
        'Pull the dumbbell up toward the hip',
        'Squeeze the back at the top',
        'Lower with control and repeat',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 28,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e26',
      name: 'Chin-Ups',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Underhand-grip pulling movement that emphasizes both back and biceps.',
      instructions: const [
        'Grip the bar with palms facing you',
        'Hang with arms fully extended',
        'Pull body up until chin clears the bar',
        'Lower with control back to start',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 38,
      defaultSets: 4,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e27',
      name: 'Face Pull',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Rear-delt and upper-back exercise that improves posture and shoulder health.',
      instructions: const [
        'Set a cable at head height with a rope attachment',
        'Pull the rope toward the face, elbows high',
        'Squeeze the shoulder blades together',
        'Return with control to the starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e28',
      name: 'Straight-Arm Pulldown',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Isolation movement that targets the lats without bicep involvement.',
      instructions: const [
        'Stand facing a high cable with a straight-bar attachment',
        'Keep arms straight and pull the bar down to the thighs',
        'Squeeze the lats at the bottom',
        'Return with control to the starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 22,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e29',
      name: 'Rack Pulls',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.compound,
      description: 'Partial deadlift variation performed from knee height to overload the upper back.',
      instructions: const [
        'Set the bar on safety pins at knee height',
        'Grip the bar and stand up tall, driving through the heels',
        'Squeeze the back at the top of the movement',
        'Lower with control back to the pins',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 48,
      defaultSets: 3,
      defaultRestSeconds: 120,
    ),
    Exercise(
      id: 'e30',
      name: 'Inverted Row',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Bodyweight rowing movement performed under a bar or rings.',
      instructions: const [
        'Lie under a bar set at hip height, gripping it with both hands',
        'Keep body straight and pull chest up to the bar',
        'Squeeze shoulder blades together',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 26,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e31',
      name: 'Meadows Row',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Landmine rowing variation that provides a unique angle for back development.',
      instructions: const [
        'Set up a barbell in a landmine attachment',
        'Stand alongside the bar and grip near the collar',
        'Row the bar up toward the hip',
        'Lower with control and repeat',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 36,
      defaultSets: 3,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e32',
      name: 'Renegade Row',
      muscleGroup: MuscleGroup.back,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.compound,
      description: 'Core-intensive rowing movement performed from a plank position with dumbbells.',
      instructions: const [
        'Start in a plank position holding a dumbbell in each hand',
        'Row one dumbbell up toward the hip while balancing on the other arm',
        'Lower with control and repeat on the other side',
        'Keep hips square throughout',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 34,
      defaultSets: 3,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e33',
      name: 'Arnold Press',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Rotational pressing movement that hits all three heads of the deltoid.',
      instructions: const [
        'Hold dumbbells in front of shoulders with palms facing you',
        'Press up while rotating palms to face forward',
        'Reverse the rotation on the way back down',
        'Repeat with controlled tempo',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 34,
      defaultSets: 4,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e34',
      name: 'Lateral Raise',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Isolation movement for building wider-looking shoulders through the side delts.',
      instructions: const [
        'Hold a dumbbell in each hand at your sides',
        'Raise arms out to the sides until shoulder height',
        'Pause briefly at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e35',
      name: 'Front Raise',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Isolation movement targeting the front deltoid.',
      instructions: const [
        'Hold a dumbbell in each hand in front of the thighs',
        'Raise arms straight in front to shoulder height',
        'Pause briefly at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e36',
      name: 'Rear Delt Fly',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Isolation movement for the often-neglected rear deltoids.',
      instructions: const [
        'Hinge forward at the hips holding a dumbbell in each hand',
        'Raise arms out to the sides, squeezing the rear shoulders',
        'Pause briefly at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e37',
      name: 'Upright Row',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Vertical pulling movement that targets shoulders and traps.',
      instructions: const [
        'Hold a barbell or EZ-bar with hands close together',
        'Pull the bar up toward the chin, elbows leading',
        'Pause briefly at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 26,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e38',
      name: 'Cable Lateral Raise',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'Cable variation of the lateral raise that provides constant tension.',
      instructions: const [
        'Stand next to a low cable pulley',
        'Raise the handle out to the side to shoulder height',
        'Pause briefly at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e39',
      name: 'Behind-the-Neck Press',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.compound,
      description: 'Advanced pressing variation requiring good shoulder mobility.',
      instructions: const [
        'Hold a barbell behind the neck at shoulder width',
        'Press the bar straight overhead',
        'Lower with control back behind the neck',
        'Keep the core braced throughout',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 36,
      defaultSets: 3,
      defaultRestSeconds: 90,
    ),
    Exercise(
      id: 'e40',
      name: 'Machine Shoulder Press',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.compound,
      description: 'Machine-based pressing movement suitable for beginners building shoulder strength.',
      instructions: const [
        'Adjust seat so handles are level with shoulders',
        'Press handles up until arms are extended',
        'Return with control back to the starting position',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 28,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e41',
      name: 'Bus Drivers',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Rotational plate movement that builds shoulder stability and endurance.',
      instructions: const [
        'Hold a weight plate with both hands in front of the chest',
        'Rotate the plate side to side like turning a steering wheel',
        'Keep arms extended and core braced throughout',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 16,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e42',
      name: 'Cuban Press',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Combination movement that builds shoulder strength and rotator cuff stability.',
      instructions: const [
        'Hold dumbbells at hip height and pull up to shoulder height, elbows high',
        'Rotate the arms so the dumbbells point overhead',
        'Press the dumbbells straight up',
        'Reverse the sequence back to the start',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 24,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e43',
      name: 'Barbell Shrugs',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Isolation movement for building the upper traps and overall shoulder girdle strength.',
      instructions: const [
        'Hold a barbell in front of the thighs with an overhand grip',
        'Shrug the shoulders straight up toward the ears',
        'Pause briefly at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e44',
      name: 'Plate Front Raise',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Simple front-delt isolation exercise using a weight plate.',
      instructions: const [
        'Hold a weight plate with both hands in front of the thighs',
        'Raise the plate straight up to shoulder height',
        'Pause briefly at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e45',
      name: 'Seated Dumbbell Press',
      muscleGroup: MuscleGroup.shoulders,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.compound,
      description: 'Seated variation of the overhead press that reduces lower-body involvement for stricter shoulder focus.',
      instructions: const [
        'Sit on a bench with back support, holding dumbbells at shoulder height',
        'Press the dumbbells straight overhead',
        'Lower with control back to shoulder height',
        'Repeat with a controlled tempo',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 32,
      defaultSets: 4,
      defaultRestSeconds: 75,
    ),
    Exercise(
      id: 'e46',
      name: 'Dumbbell Hammer Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Neutral-grip curl variation that also builds the brachialis and forearms.',
      instructions: const [
        'Hold a dumbbell in each hand with palms facing each other',
        'Curl the dumbbells up while keeping the wrists neutral',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e47',
      name: 'Preacher Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'Isolation curl performed on a preacher bench that removes momentum from the lift.',
      instructions: const [
        'Sit at a preacher bench with the back of the upper arms resting on the pad',
        'Curl the bar up while keeping the upper arms fixed',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e48',
      name: 'Concentration Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Seated single-arm curl that maximizes bicep isolation and mind-muscle connection.',
      instructions: const [
        'Sit on a bench and brace the elbow against the inner thigh',
        'Curl the dumbbell up toward the shoulder',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 16,
      defaultSets: 3,
      defaultRestSeconds: 45,
    ),
    Exercise(
      id: 'e49',
      name: 'Cable Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Cable-based curl that provides constant tension throughout the movement.',
      instructions: const [
        'Stand facing a low cable with a straight-bar attachment',
        'Curl the bar up toward the shoulders',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e50',
      name: 'Incline Dumbbell Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'Curl variation performed on an incline bench that increases the stretch on the biceps.',
      instructions: const [
        'Sit back on an incline bench holding a dumbbell in each hand',
        'Curl the dumbbells up while keeping the upper arms still',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e51',
      name: 'EZ-Bar Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Classic curl variation using an EZ-bar to reduce wrist strain.',
      instructions: const [
        'Hold the EZ-bar with an underhand grip on the angled portion',
        'Curl the bar up toward the shoulders',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e52',
      name: 'Spider Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'Curl performed while leaning chest-first over an incline bench for strict isolation.',
      instructions: const [
        'Lean over the high side of an incline bench, arms hanging straight down',
        'Curl the weight up while keeping the upper arms fixed',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e53',
      name: 'Zottman Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'Curl variation that combines a regular curl up with a reverse curl down for full arm development.',
      instructions: const [
        'Curl the dumbbells up with palms facing forward',
        'Rotate the palms to face down at the top',
        'Lower the dumbbells slowly with palms facing down',
        'Rotate back to the start and repeat',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 22,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e54',
      name: 'Reverse Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.beginner,
      category: ExerciseCategory.isolation,
      description: 'Overhand-grip curl that shifts emphasis to the forearms and brachialis.',
      instructions: const [
        'Hold a barbell with an overhand grip',
        'Curl the bar up while keeping wrists straight',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 18,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e55',
      name: 'Drag Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.intermediate,
      category: ExerciseCategory.isolation,
      description: 'Curl variation where the bar is dragged up the torso to keep constant bicep tension.',
      instructions: const [
        'Hold a barbell with an underhand grip close to the thighs',
        'Drag the bar up along the torso, elbows moving back',
        'Squeeze at the top',
        'Lower with control back to the start',
      ],
      estimatedMinutes: 3,
      estimatedKcal: 20,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
    Exercise(
      id: 'e56',
      name: '21s Bicep Curl',
      muscleGroup: MuscleGroup.biceps,
      difficulty: ExerciseDifficulty.advanced,
      category: ExerciseCategory.isolation,
      description: 'High-volume curl technique split into three seven-rep partial ranges for intense bicep fatigue.',
      instructions: const [
        'Curl the bar through the bottom half range for 7 reps',
        'Curl the bar through the top half range for 7 reps',
        'Curl the bar through the full range for 7 reps',
        'Keep strict form throughout all three phases',
      ],
      estimatedMinutes: 4,
      estimatedKcal: 26,
      defaultSets: 3,
      defaultRestSeconds: 60,
    ),
  ];
}