import 'package:dartz/dartz.dart';

import '../models/exercise_model.dart';
import '../models/workout_program_model.dart';

abstract class WorkoutProgramRepository {
  Future<Either<String, List<WorkoutProgram>>> getPrograms();
}

class WorkoutProgramRepositoryImpl implements WorkoutProgramRepository {
  @override
  Future<Either<String, List<WorkoutProgram>>> getPrograms() async {
    try {
      await Future.delayed(const Duration(milliseconds: 300));
      return Right(_mockPrograms);
    } catch (e) {
      return const Left('প্রোগ্রাম লোড করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।');
    }
  }

  static const List<WorkoutProgram> _mockPrograms = [
    WorkoutProgram(
      id: 'p1',
      title: 'Beginner Muscle Gain - 3 Day Split',
      description: 'Perfect for beginners looking to build muscle with a simple 3-day full body routine.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 12,
      daysPerWeek: 3,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p2',
      title: 'Intermediate Push/Pull/Legs',
      description: 'Classic 6-day split for intermediate lifters focused on muscle hypertrophy.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 12,
      daysPerWeek: 6,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p3',
      title: 'Advanced Upper/Lower Split',
      description: 'High-volume 4-day split for advanced lifters seeking maximum hypertrophy.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 16,
      daysPerWeek: 4,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p4',
      title: 'Full Body Fat Loss Circuit',
      description: 'A high-intensity full body circuit designed to burn calories and preserve lean muscle.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'WeightLoss',
    ),
    WorkoutProgram(
      id: 'p5',
      title: 'Lean & Toned - 4 Day Split',
      description: 'Moderate-intensity split combining strength and cardio for a leaner physique.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 10,
      daysPerWeek: 4,
      goalTag: 'WeightLoss',
    ),
    WorkoutProgram(
      id: 'p6',
      title: 'Shred Phase - Advanced HIIT',
      description: 'Aggressive fat-loss program pairing resistance training with metabolic finishers.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 8,
      daysPerWeek: 5,
      goalTag: 'WeightLoss',
    ),
    WorkoutProgram(
      id: 'p7',
      title: 'Beginner Strength Foundations',
      description: 'Introduces the big compound lifts with a focus on form and progressive overload.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'Strength',
    ),
    WorkoutProgram(
      id: 'p8',
      title: 'Intermediate 5x5 Strength',
      description: 'Classic 5x5 rep scheme across major lifts to build raw strength.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 12,
      daysPerWeek: 4,
      goalTag: 'Strength',
    ),
    WorkoutProgram(
      id: 'p9',
      title: 'Advanced Powerbuilding',
      description: 'Combines heavy powerlifting-style sets with bodybuilding accessory work.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 16,
      daysPerWeek: 5,
      goalTag: 'Strength',
    ),
    WorkoutProgram(
      id: 'p10',
      title: 'Home Workout - No Equipment',
      description: 'Bodyweight-only program for building strength and endurance anywhere.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 6,
      daysPerWeek: 4,
      goalTag: 'GeneralFitness',
    ),
    WorkoutProgram(
      id: 'p11',
      title: 'Functional Fitness Builder',
      description: 'Improves everyday movement patterns, balance, and core stability.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 10,
      daysPerWeek: 4,
      goalTag: 'GeneralFitness',
    ),
    WorkoutProgram(
      id: 'p12',
      title: 'Total Body Conditioning',
      description: 'Well-rounded program mixing strength, mobility, and light cardio.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'GeneralFitness',
    ),
    WorkoutProgram(
      id: 'p13',
      title: 'Beginner Bro Split',
      description: '5-day split targeting one or two muscle groups per session for beginners easing into splits.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 10,
      daysPerWeek: 5,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p14',
      title: 'Classic Bro Split - 5 Day',
      description: 'Traditional bodybuilding split: chest, back, legs, shoulders, arms.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 12,
      daysPerWeek: 5,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p15',
      title: 'Advanced Arnold Split',
      description: 'High-volume 6-day split inspired by golden-era bodybuilding routines.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 16,
      daysPerWeek: 6,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p16',
      title: 'Upper/Lower for Mass',
      description: '4-day upper/lower split emphasizing progressive overload for hypertrophy.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 12,
      daysPerWeek: 4,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p17',
      title: 'Push Pull Legs - Beginner',
      description: 'Simplified 3-day PPL rotation ideal for those new to split training.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p18',
      title: 'Advanced PPL - 6 Day',
      description: 'High-frequency push/pull/legs rotation repeated twice per week.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 16,
      daysPerWeek: 6,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p19',
      title: 'Endurance Runner Strength Support',
      description: 'Strength training designed to complement running programs and prevent injury.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 10,
      daysPerWeek: 3,
      goalTag: 'Endurance',
    ),
    WorkoutProgram(
      id: 'p20',
      title: 'Cardio & Core Endurance',
      description: 'Builds cardiovascular endurance alongside core stability work.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 4,
      goalTag: 'Endurance',
    ),
    WorkoutProgram(
      id: 'p21',
      title: 'Advanced Metabolic Conditioning',
      description: 'Circuit-style conditioning sessions to push aerobic and anaerobic capacity.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 10,
      daysPerWeek: 5,
      goalTag: 'Endurance',
    ),
    WorkoutProgram(
      id: 'p22',
      title: 'Glute & Leg Specialization',
      description: 'Lower-body focused program to build strength and shape in the glutes and legs.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 12,
      daysPerWeek: 4,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p23',
      title: 'Beginner Glute Builder',
      description: 'Introductory lower-body program focused on glute activation and growth.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p24',
      title: 'Advanced Leg Day Overload',
      description: 'High-volume leg-focused program for advanced lifters chasing lower-body growth.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 12,
      daysPerWeek: 2,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p25',
      title: 'Core & Abs Sculpt',
      description: 'Dedicated core program to build strength and definition in the midsection.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 6,
      daysPerWeek: 3,
      goalTag: 'GeneralFitness',
    ),
    WorkoutProgram(
      id: 'p26',
      title: 'Beginner 3 Day Full Body',
      description: 'Simple full-body routine hitting all major muscle groups three times a week.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p27',
      title: 'Intermediate Full Body Strength',
      description: 'Full-body sessions with heavier loads for continued strength progress.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 10,
      daysPerWeek: 3,
      goalTag: 'Strength',
    ),
    WorkoutProgram(
      id: 'p28',
      title: 'Advanced Full Body Power',
      description: 'Explosive full-body sessions combining strength and power development.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 12,
      daysPerWeek: 4,
      goalTag: 'Strength',
    ),
    WorkoutProgram(
      id: 'p29',
      title: 'Women\'s Strength Starter',
      description: 'Beginner-friendly strength program designed to build confidence with weights.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'Strength',
    ),
    WorkoutProgram(
      id: 'p30',
      title: 'Athletic Performance Builder',
      description: 'Combines strength, power, and agility work for general athletic performance.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 12,
      daysPerWeek: 4,
      goalTag: 'GeneralFitness',
    ),
    WorkoutProgram(
      id: 'p31',
      title: 'Old School Bodybuilding',
      description: 'High-volume classic bodybuilding split emphasizing time under tension.',
      difficulty: ExerciseDifficulty.advanced,
      weeks: 14,
      daysPerWeek: 5,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p32',
      title: 'Beginner Upper Body Focus',
      description: 'Simple upper-body strength program for beginners wanting faster upper-body gains.',
      difficulty: ExerciseDifficulty.beginner,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'MuscleGain',
    ),
    WorkoutProgram(
      id: 'p33',
      title: 'Intermediate Arms & Shoulders',
      description: 'Dedicated arm and shoulder hypertrophy program for visible arm growth.',
      difficulty: ExerciseDifficulty.intermediate,
      weeks: 8,
      daysPerWeek: 3,
      goalTag: 'MuscleGain',
    ),
  ];
}