import '../models/food_item_model.dart';

class FoodCalorieRepository {
  Future<List<FoodItem>> getItems(FoodCategory category) async {
    await Future.delayed(const Duration(milliseconds: 200));
    return _data[category] ?? const [];
  }

  static const Map<FoodCategory, List<FoodItem>> _data = {
    FoodCategory.fat: [
      // === FAT CATEGORY (30 items) ===
      FoodItem(name: 'আখরোট', amountLabel: '১ মুঠো', caloriesLabel: '১৮৫'),
      FoodItem(name: 'চারমগজ', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৫০'),
      FoodItem(name: 'তিসি বীজ', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৫৫'),
      FoodItem(name: 'তিল বীজ', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৫২'),
      FoodItem(name: 'নারকেল (কোরানো)', amountLabel: '১ কাপ', caloriesLabel: '২৮৩'),
      FoodItem(name: 'নারকেল তেল', amountLabel: '১ টেবিল চামচ', caloriesLabel: '১২১'),
      FoodItem(name: 'সরিষার তেল', amountLabel: '১ টেবিল চামচ', caloriesLabel: '১২৪'),
      FoodItem(name: 'মাখন', amountLabel: '১ টেবিল চামচ', caloriesLabel: '১০২'),
      FoodItem(name: 'চিজ', amountLabel: '১ স্লাইস', caloriesLabel: '১১৩'),
      FoodItem(name: 'ক্রিম', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৫২'),
      FoodItem(name: 'মেয়োনিজ', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৯৪'),
      FoodItem(name: 'চিকেন ফ্রাই', amountLabel: '১ পিস', caloriesLabel: '২৮৫'),
      FoodItem(name: 'মাছ ভাজা', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৫০'),
      FoodItem(name: 'সমুচা', amountLabel: '১টি', caloriesLabel: '১৩২'),
      FoodItem(name: 'পিঁয়াজু', amountLabel: '১টি', caloriesLabel: '৭৮'),
      FoodItem(name: 'বেগুনি', amountLabel: '১টি', caloriesLabel: '৯০'),
      FoodItem(name: 'আলুর চপ', amountLabel: '১টি', caloriesLabel: '১১৬'),
      FoodItem(name: 'ডিম ভাজা (তেলে)', amountLabel: '১টি', caloriesLabel: '৯০'),
      FoodItem(name: 'খিচুড়ি (ঘি দিয়ে)', amountLabel: '১ কাপ', caloriesLabel: '৩২০'),
      FoodItem(name: 'ফ্রেঞ্চ ফ্রাই', amountLabel: '১ কাপ', caloriesLabel: '৩১২'),
      FoodItem(name: 'আলুর চিপস', amountLabel: '১ প্যাকেট (৩০ গ্রাম)', caloriesLabel: '১৬০'),
      FoodItem(name: 'আইসক্রিম', amountLabel: '১ স্কুপ', caloriesLabel: '১৩৭'),
      FoodItem(name: 'চকলেট (দুধ)', amountLabel: '১ বার (৪০ গ্রাম)', caloriesLabel: '২১২'),
      FoodItem(name: 'বাদাম মাখন', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৯৪'),
      FoodItem(name: 'ফুলুরি', amountLabel: '১টি', caloriesLabel: '৭০'),
      FoodItem(name: 'মালাই', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৫০'),
      FoodItem(name: 'খাসির মাংস (চর্বিসহ)', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৯৪'),
      FoodItem(name: 'সসেজ', amountLabel: '১টি', caloriesLabel: '১৫০'),
      FoodItem(name: 'বেকন', amountLabel: '২ স্লাইস', caloriesLabel: '৮৯'),
      FoodItem(name: 'অ্যাভোকাডো', amountLabel: '১টি মাঝারি', caloriesLabel: '২৩৪'),
    ],
    FoodCategory.sugar: [
      // === SUGAR/CARB CATEGORY (32 items) ===
      FoodItem(name: 'খই', amountLabel: '১ কাপ', caloriesLabel: '১১০'),
      FoodItem(name: 'চিড়া', amountLabel: '১ কাপ', caloriesLabel: '২৭০'),
      FoodItem(name: 'মুড়ি', amountLabel: '১ কাপ', caloriesLabel: '৪৩'),
      FoodItem(name: 'সেমাই (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২১০'),
      FoodItem(name: 'ফিরনি', amountLabel: '১ বাটি', caloriesLabel: '২২০'),
      FoodItem(name: 'পায়েস', amountLabel: '১ বাটি', caloriesLabel: '২৩৫'),
      FoodItem(name: 'জিলাপি', amountLabel: '১টি', caloriesLabel: '১৫০'),
      FoodItem(name: 'চমচম', amountLabel: '১টি', caloriesLabel: '১৬৪'),
      FoodItem(name: 'সন্দেশ', amountLabel: '১টি', caloriesLabel: '৯০'),
      FoodItem(name: 'লাড্ডু', amountLabel: '১টি', caloriesLabel: '১৮৬'),
      FoodItem(name: 'হালুয়া (সুজির)', amountLabel: '১ কাপ', caloriesLabel: '৩৫০'),
      FoodItem(name: 'আঙুর', amountLabel: '১ কাপ', caloriesLabel: '১০৪'),
      FoodItem(name: 'আপেল', amountLabel: '১টি মাঝারি', caloriesLabel: '৯৫'),
      FoodItem(name: 'কমলা', amountLabel: '১টি মাঝারি', caloriesLabel: '৬২'),
      FoodItem(name: 'আনারস', amountLabel: '১ কাপ কুচি', caloriesLabel: '৮২'),
      FoodItem(name: 'পেঁপে', amountLabel: '১ কাপ কুচি', caloriesLabel: '৬২'),
      FoodItem(name: 'তরমুজ', amountLabel: '১ কাপ কুচি', caloriesLabel: '৪৬'),
      FoodItem(name: 'খেজুর', amountLabel: '৩টি', caloriesLabel: '৬৬'),
      FoodItem(name: 'কিশমিশ', amountLabel: '১ মুঠো', caloriesLabel: '১২৯'),
      FoodItem(name: 'গুড়', amountLabel: '১ টেবিল চামচ', caloriesLabel: '৫৯'),
      FoodItem(name: 'কোমল পানীয় (কোলা)', amountLabel: '১ ক্যান', caloriesLabel: '১৪০'),
      FoodItem(name: 'আমের জুস', amountLabel: '১ গ্লাস', caloriesLabel: '১৩৪'),
      FoodItem(name: 'মিষ্টি বিস্কুট', amountLabel: '২টি', caloriesLabel: '৯০'),
      FoodItem(name: 'কেক', amountLabel: '১ স্লাইস', caloriesLabel: '২৩৫'),
      FoodItem(name: 'ডোনাট', amountLabel: '১টি', caloriesLabel: '২৫০'),
      FoodItem(name: 'পাস্তা (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২২১'),
      FoodItem(name: 'নুডলস (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২২০'),
      FoodItem(name: 'ওটমিল (মিষ্টিসহ)', amountLabel: '১ বাটি', caloriesLabel: '১৬৬'),
      FoodItem(name: 'কর্ন ফ্লেক্স', amountLabel: '১ কাপ', caloriesLabel: '১০০'),
      FoodItem(name: 'পোলাও (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২১০'),
      FoodItem(name: 'মিষ্টি চা', amountLabel: '১ কাপ', caloriesLabel: '৪০'),
      FoodItem(name: 'মিষ্টি আইসড টি', amountLabel: '১ গ্লাস', caloriesLabel: '৯০'),
    ],
    FoodCategory.protein: [
      // === PROTEIN CATEGORY (30 items) ===
      FoodItem(name: 'খাসির মাংস (রান্না)', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৯৪'),
      FoodItem(name: 'হাঁসের মাংস (রান্না)', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৩৭'),
      FoodItem(name: 'কবুতরের মাংস', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৩৬'),
      FoodItem(name: 'চিংড়ি (রান্না)', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯৯'),
      FoodItem(name: 'কাতল মাছ', amountLabel: '১০০ গ্রাম', caloriesLabel: '১১১'),
      FoodItem(name: 'পাবদা মাছ', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯০'),
      FoodItem(name: 'কই মাছ', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯৫'),
      FoodItem(name: 'শোল মাছ', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯৪'),
      FoodItem(name: 'টেংরা মাছ', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯৬'),
      FoodItem(name: 'সামুদ্রিক মাছ', amountLabel: '১০০ গ্রাম', caloriesLabel: '১০৫'),
      FoodItem(name: 'মসুর ডাল (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২৩০'),
      FoodItem(name: 'ছোলা (সিদ্ধ)', amountLabel: '১ কাপ', caloriesLabel: '২৬৯'),
      FoodItem(name: 'রাজমা (সিদ্ধ)', amountLabel: '১ কাপ', caloriesLabel: '২২৫'),
      FoodItem(name: 'সয়াবিন (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২৯৮'),
      FoodItem(name: 'টোফু', amountLabel: '১০০ গ্রাম', caloriesLabel: '৭৬'),
      FoodItem(name: 'হুই প্রোটিন', amountLabel: '১ স্কুপ', caloriesLabel: '১২০'),
      FoodItem(name: 'ছানা', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৬৫'),
      FoodItem(name: 'বাদাম দুধ', amountLabel: '১ কাপ', caloriesLabel: '৩৯'),
      FoodItem(name: 'সয়া দুধ', amountLabel: '১ কাপ', caloriesLabel: '৮০'),
      FoodItem(name: 'ডিমের সাদা অংশ', amountLabel: '১টি', caloriesLabel: '১৭'),
      FoodItem(name: 'মুরগির বুকের মাংস', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৬৫'),
      FoodItem(name: 'মুরগির রানের মাংস', amountLabel: '১০০ গ্রাম', caloriesLabel: '২০৯'),
      FoodItem(name: 'গরুর কলিজা', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৭৫'),
      FoodItem(name: 'মুরগির কলিজা', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৬৭'),
      FoodItem(name: 'চিনাবাদাম', amountLabel: '১ মুঠো', caloriesLabel: '১৭০'),
      FoodItem(name: 'মটর ডাল (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২৩১'),
      FoodItem(name: 'মুগ ডাল (রান্না)', amountLabel: '১ কাপ', caloriesLabel: '২১২'),
      FoodItem(name: 'খাসির কলিজা', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৩৭'),
      FoodItem(name: 'কাঁকড়ার মাংস', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯৭'),
      FoodItem(name: 'স্কিম মিল্ক', amountLabel: '১ কাপ', caloriesLabel: '৮৩'),
    ],
    FoodCategory.general: [
      // === GENERAL CATEGORY (30 items) ===
      FoodItem(name: 'ফুলকপি', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৫'),
      FoodItem(name: 'বাঁধাকপি', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৫'),
      FoodItem(name: 'বেগুন', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৫'),
      FoodItem(name: 'ঢেঁড়স', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৩'),
      FoodItem(name: 'লাউ', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৪'),
      FoodItem(name: 'মিষ্টি কুমড়া', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৬'),
      FoodItem(name: 'করলা', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৭'),
      FoodItem(name: 'শসা', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৫'),
      FoodItem(name: 'টমেটো', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৮'),
      FoodItem(name: 'পালং শাক', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৩'),
      FoodItem(name: 'লাল শাক', amountLabel: '১০০ গ্রাম', caloriesLabel: '২৩'),
      FoodItem(name: 'মুলা', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৬'),
      FoodItem(name: 'শিম', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৪'),
      FoodItem(name: 'কাঁচা কলা', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯০'),
      FoodItem(name: 'মিষ্টি আলু', amountLabel: '১০০ গ্রাম', caloriesLabel: '৮৬'),
      FoodItem(name: 'ভুট্টা', amountLabel: '১০০ গ্রাম', caloriesLabel: '৯৬'),
      FoodItem(name: 'ওটস (কাঁচা)', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৮৯'),
      FoodItem(name: 'ময়দা', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৬৪'),
      FoodItem(name: 'সুজি', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৬০'),
      FoodItem(name: 'আটা', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৪০'),
      FoodItem(name: 'পোলাও চাল (কাঁচা)', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৬৫'),
      FoodItem(name: 'সাগু', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৫২'),
      FoodItem(name: 'বার্লি', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৫৪'),
      FoodItem(name: 'মটরশুঁটি', amountLabel: '১০০ গ্রাম', caloriesLabel: '৮১'),
      FoodItem(name: 'ব্রকলি', amountLabel: '১০০ গ্রাম', caloriesLabel: '৩৪'),
      FoodItem(name: 'ক্যাপসিকাম', amountLabel: '১০০ গ্রাম', caloriesLabel: '২০'),
      FoodItem(name: 'পেঁয়াজ', amountLabel: '১০০ গ্রাম', caloriesLabel: '৪০'),
      FoodItem(name: 'রসুন', amountLabel: '১০০ গ্রাম', caloriesLabel: '১৪৯'),
      FoodItem(name: 'আদা', amountLabel: '১০০ গ্রাম', caloriesLabel: '৮০'),
      FoodItem(name: 'কাঁচা মরিচ', amountLabel: '১০০ গ্রাম', caloriesLabel: '৪০'),
    ],
  };
}